steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fabled-variety-351411/mindjoy-api:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fabled-variety-351411/mindjoy-api:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'deploy', 'mindjoy-api', '--region=asia-southeast1' , '--platform=managed', '--image=gcr.io/fabled-variety-351411/mindjoy-api:$SHORT_SHA']